name: setup project
on: [push]
jobs:
  setup-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - run: make setup
      - run: make lint
      - run: make test
